module ir_stream_bidir_vec_bd #(
  parameter integer LANE_COUNT       = 2,
  parameter integer B_SESSION_ID     = 16'h2203,
  parameter integer B_CNT_CHIP_MAX   = 15,
  parameter integer B_CNT_PREAMBLE   = 64,
  parameter integer B_RX_DATA_PHASE_DELAY_CYCLES = 0,
  parameter integer B_RX_DETECT_START_CYCLES = (B_CNT_CHIP_MAX >= 15) ? 0 : ((B_CNT_CHIP_MAX >= 7) ? 3 : 0),
  parameter integer B_RX_DETECT_END_CYCLES = (B_CNT_CHIP_MAX >= 15) ? 10 : B_CNT_CHIP_MAX,
  parameter integer B_RX_PREAMBLE_REALIGN_EDGE = 0,
  parameter integer B_GUARD_CYCLES   = 1408,
  parameter integer B_BACKOFF_SLOT_CYCLES = 1024,
  parameter integer B_START_IDLE_CYCLES = 100000,
  parameter integer B_RECOVERY_RESET_CYCLES = 2048,
  parameter integer B_PARALLEL_2LANE_MODE = 0,
  parameter integer B_DEBUG_SELECT_RX_STATUS = 0,
  parameter integer B_ACK_LANE_MASK = -1,
  parameter integer B_TX_LANE_MASK = -1,
  parameter integer B_RX_LANE_MASK = -1,
  parameter integer B_EXPECTED_A_LANE_MASK = -1,
  parameter integer RAW_PACKET_BYTES = 255,
  parameter integer FRAGMENT_BYTES   = 128,
  parameter integer APP_PAYLOAD_BYTES = 247,
  parameter integer B2A_ENABLE      = 1,
  parameter integer B2A_FREE_RUN    = 0,
  parameter integer B2A_ECHO_ENABLE = 0,
  parameter integer FORCE_SD_SHUTDOWN = 0,
  parameter integer TX_GAP_CYCLES    = 0
)(
  input  wire                  clk_phy,
  input  wire                  rst_n,
  output wire [LANE_COUNT-1:0] ir_tx_out,
  input  wire [LANE_COUNT-1:0] ir_rx_in,
  output wire [LANE_COUNT-1:0] ir_sd,
  output wire [LANE_COUNT-1:0] ir_mode_out,
  output wire [31:0]           debug_status
);
  ir_stream_bidir_b0_core #(
    .LANE_COUNT(LANE_COUNT),
    .B_SESSION_ID(B_SESSION_ID),
    .B_CNT_CHIP_MAX(B_CNT_CHIP_MAX),
    .B_CNT_PREAMBLE(B_CNT_PREAMBLE),
    .B_RX_DATA_PHASE_DELAY_CYCLES(B_RX_DATA_PHASE_DELAY_CYCLES),
    .B_RX_DETECT_START_CYCLES(B_RX_DETECT_START_CYCLES),
    .B_RX_DETECT_END_CYCLES(B_RX_DETECT_END_CYCLES),
    .B_RX_PREAMBLE_REALIGN_EDGE(B_RX_PREAMBLE_REALIGN_EDGE),
    .B_GUARD_CYCLES(B_GUARD_CYCLES),
    .B_BACKOFF_SLOT_CYCLES(B_BACKOFF_SLOT_CYCLES),
    .B_START_IDLE_CYCLES(B_START_IDLE_CYCLES),
    .B_RECOVERY_RESET_CYCLES(B_RECOVERY_RESET_CYCLES),
    .B_PARALLEL_2LANE_MODE(B_PARALLEL_2LANE_MODE),
    .B_DEBUG_SELECT_RX_STATUS(B_DEBUG_SELECT_RX_STATUS),
    .B_ACK_LANE_MASK(B_ACK_LANE_MASK),
    .B_TX_LANE_MASK(B_TX_LANE_MASK),
    .B_RX_LANE_MASK(B_RX_LANE_MASK),
    .B_EXPECTED_A_LANE_MASK(B_EXPECTED_A_LANE_MASK),
    .RAW_PACKET_BYTES(RAW_PACKET_BYTES),
    .FRAGMENT_BYTES(FRAGMENT_BYTES),
    .APP_PAYLOAD_BYTES(APP_PAYLOAD_BYTES),
    .B2A_ENABLE(B2A_ENABLE),
    .B2A_FREE_RUN(B2A_FREE_RUN),
    .B2A_ECHO_ENABLE(B2A_ECHO_ENABLE),
    .FORCE_SD_SHUTDOWN(FORCE_SD_SHUTDOWN),
    .TX_GAP_CYCLES(TX_GAP_CYCLES)
  ) u_core (
    .clk_phy(clk_phy),
    .rst_n(rst_n),
    .ir_tx_out(ir_tx_out),
    .ir_rx_in(ir_rx_in),
    .ir_sd(ir_sd),
    .ir_mode_out(ir_mode_out),
    .debug_status(debug_status)
  );
endmodule
