from __future__ import annotations

import copy
import hashlib
import json
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import finalize_p10_4_interrupted_run as interrupted  # noqa: E402
import run_p10_4_hardware as campaign  # noqa: E402
import run_p10_4_resume_hardware as resume  # noqa: E402


class P104ResumeTests(unittest.TestCase):
    def test_resume_is_exact_contiguous_suffix(self) -> None:
        self.assertEqual(54, len(campaign.STAGES))
        self.assertEqual(42, len(resume.PREFIX_STAGES))
        self.assertEqual(12, len(resume.RESUME_STAGES))
        self.assertEqual("pl_recovery_rotating_1", resume.PREFIX_STAGES[-1])
        self.assertEqual("pl_reset_rotating_2", resume.RESUME_STAGES[0])
        self.assertEqual("mixed_15min_b", resume.RESUME_STAGES[-1])
        self.assertEqual(
            campaign.STAGES,
            resume.PREFIX_STAGES + resume.RESUME_STAGES,
        )
        self.assertEqual(
            resume.RESUME_STAGES,
            campaign.STAGES[len(interrupted.COMPLETED_PREFIX):],
        )

    def test_resume_plan_hashes_are_original_selected_plans(self) -> None:
        parent = (
            campaign.HW_ROOT / interrupted.DEFAULT_PARENT_RUN_ID /
            "stages/tuning/stage_summary.json"
        )
        selected = json.loads(parent.read_text(encoding="utf-8"))["semantics"][
            "selected"
        ]
        plans = campaign.build_plans(selected)
        for stage in resume.RESUME_STAGES:
            self.assertEqual(
                campaign.sha256(
                    campaign.HW_ROOT / interrupted.DEFAULT_PARENT_RUN_ID /
                    "stages" / stage / "immutable.plan"
                ) if (
                    campaign.HW_ROOT / interrupted.DEFAULT_PARENT_RUN_ID /
                    "stages" / stage / "immutable.plan"
                ).is_file() else None,
                hashlib.sha256(plans[stage].encode("ascii")).hexdigest()
                if (
                    campaign.HW_ROOT / interrupted.DEFAULT_PARENT_RUN_ID /
                    "stages" / stage / "immutable.plan"
                ).is_file() else None,
            )

    def test_parent_run_directly_verifies_as_resumable(self) -> None:
        run_root = campaign.HW_ROOT / interrupted.DEFAULT_PARENT_RUN_ID
        verified, errors = interrupted.verify_parent_run(run_root)
        self.assertEqual([], errors)
        self.assertEqual("buffers4_batch32", verified["selected_config"]["name"])
        self.assertEqual("PASS", verified["interruption"]["status"])
        self.assertTrue(verified["interruption"]["reexecution_required"])
        self.assertLessEqual(
            verified["interruption"]["measured_runtime_seconds"], 1800
        )

    def test_resume_runner_enforces_shutdown_runtime_and_cooldown(self) -> None:
        source = Path(resume.__file__).read_text(encoding="utf-8")
        for marker in (
            "runtime_guard.wait_for_cooldown()",
            "runtime_guard.begin_stage",
            "runtime_guard.finish_stage",
            "shutdown-before unconfirmed",
            "shutdown-after unconfirmed",
            "finally",
            "force_abort=True",
        ):
            self.assertIn(marker, source)
        self.assertIn("for stage in RESUME_STAGES", source)
        self.assertNotIn("Ethernet", source)
        self.assertTrue(all(
            campaign.stage_timeout(stage) <= 1200
            for stage in resume.RESUME_STAGES
        ))

    def test_parent_checkpoint_mutation_is_rejected_when_present(self) -> None:
        if not resume.PARENT_CHECKPOINT.is_file():
            self.skipTest("parent checkpoint is generated by the interrupted-run finalizer")
        checkpoint = json.loads(
            resume.PARENT_CHECKPOINT.read_text(encoding="utf-8")
        )
        prefix, selected, parent_root, errors = \
            resume.validate_parent_checkpoint(checkpoint)
        self.assertEqual([], errors)
        self.assertEqual(len(resume.PREFIX_STAGES), len(prefix))
        self.assertEqual("buffers4_batch32", selected["name"])
        self.assertEqual(interrupted.DEFAULT_PARENT_RUN_ID, parent_root.name)
        mutated = copy.deepcopy(checkpoint)
        mutated["completed_stages"] = mutated["completed_stages"][:-1]
        _, _, _, mutation_errors = resume.validate_parent_checkpoint(mutated)
        self.assertTrue(mutation_errors)


if __name__ == "__main__":
    unittest.main()
