set repo_root [file normalize [file join [file dirname [info script]] ..]]
set project_file [file join $repo_root TFDU_VFIR_Client_Array TFDU_VFIR_Client.xpr]
set ip_repo [file join $repo_root IPs ip_ir_array]
set out_dir [file join $repo_root TFDU_VFIR_Client_Array direct_build]
set xsa_file [file join $repo_root TFDU_VFIR_Client_Array design_shiboqi_wrapper.xsa]
set bit_copy [file join $repo_root TFDU_VFIR_Client_Array design_shiboqi_wrapper.bit]

if {![file exists $project_file]} {
  error "Missing Vivado project: $project_file"
}

set max_threads 16
if {[info exists ::env(VIVADO_MAX_THREADS)] && $::env(VIVADO_MAX_THREADS) ne ""} {
  set max_threads $::env(VIVADO_MAX_THREADS)
}

set_param general.maxThreads $max_threads
open_project $project_file
set_property ip_repo_paths $ip_repo [current_project]
update_ip_catalog -rebuild

set bd_file [lindex [get_files -quiet */design_shiboqi.bd] 0]
if {$bd_file eq ""} {
  error "Missing design_shiboqi.bd in project"
}

file mkdir $out_dir
reset_target all $bd_file
generate_target all $bd_file
export_ip_user_files -of_objects $bd_file -no_script -sync -force -quiet
update_compile_order -fileset sources_1

set bd_gen_dir [file normalize [file join $repo_root TFDU_VFIR_Client_Array TFDU_VFIR_Client.gen sources_1 bd design_shiboqi ip]]
set auto_synth_files [list]
if {[file exists $bd_gen_dir]} {
  set auto_synth_files [glob -nocomplain -directory $bd_gen_dir -types f design_shiboqi_auto_*/synth/*.v]
}

proc write_blackbox_stub_from_synth {out_fh src_file} {
  set in_fh [open $src_file r]
  set text [read $in_fh]
  close $in_fh

  set started 0
  foreach line [split $text "\n"] {
    if {!$started} {
      if {[regexp {^\s*module\s+([A-Za-z0-9_]+)} $line]} {
        puts $out_fh "(* black_box = \"true\" *)"
        puts $out_fh $line
        set started 1
      }
      continue
    }

    if {[regexp {^\s+[A-Za-z][A-Za-z0-9_]*_v[0-9][A-Za-z0-9_]*\s*#\s*\(} $line]} {
      puts $out_fh "endmodule"
      puts $out_fh ""
      return
    }
    puts $out_fh $line
  }

  error "Could not find internal IP instance while generating stub from $src_file"
}

set generated_stub_file [file join $out_dir auto_blackbox_stubs.v]
set stub_fh [open $generated_stub_file w]
puts $stub_fh "// Generated by build_direct_bitstream.tcl for direct synthesis."
foreach synth_file [lsort -unique $auto_synth_files] {
  write_blackbox_stub_from_synth $stub_fh $synth_file
}
close $stub_fh
if {[llength [lsort -unique $auto_synth_files]] > 0} {
  read_verilog $generated_stub_file
}
puts "DIRECT_BUILD_GENERATED_AUTO_STUBS=[llength [lsort -unique $auto_synth_files]]"

set part_name [get_property PART [current_project]]
set constrset_name [get_property constrset [current_run -synthesis]]
if {$constrset_name eq ""} {
  set constrset_name constrs_1
}

puts "DIRECT_BUILD_SYNTH top=design_shiboqi_wrapper part=$part_name constrset=$constrset_name threads=$max_threads"
synth_design -top design_shiboqi_wrapper -part $part_name -constrset $constrset_name

set ip_dcp_files [list]
if {[file exists $bd_gen_dir]} {
  set ip_dcp_files [glob -nocomplain -directory $bd_gen_dir -types f */*.dcp]
}
set bound_dcp_count 0
foreach dcp_file [lsort -unique $ip_dcp_files] {
  set ref_name [file rootname [file tail $dcp_file]]
  foreach cell [get_cells -quiet -hier -filter "REF_NAME == $ref_name"] {
    if {[catch {read_checkpoint -quiet -cell $cell $dcp_file} msg]} {
      puts "DIRECT_BUILD_DCP_SKIP cell=$cell ref=$ref_name reason=$msg"
    } else {
      incr bound_dcp_count
      puts "DIRECT_BUILD_DCP_BOUND cell=$cell ref=$ref_name"
    }
  }
}
puts "DIRECT_BUILD_DCP_BOUND_COUNT=$bound_dcp_count"

write_checkpoint -force [file join $out_dir design_shiboqi_wrapper_synth.dcp]
report_utilization -file [file join $out_dir utilization_synth.rpt]

puts "DIRECT_BUILD_IMPL"
opt_design
write_checkpoint -force [file join $out_dir design_shiboqi_wrapper_opt.dcp]
place_design
write_checkpoint -force [file join $out_dir design_shiboqi_wrapper_placed.dcp]
route_design
write_checkpoint -force [file join $out_dir design_shiboqi_wrapper_routed.dcp]

report_drc -file [file join $out_dir drc_routed.rpt]
report_timing_summary -file [file join $out_dir timing_summary_post_route.rpt]
report_utilization -file [file join $out_dir utilization_post_route.rpt]
report_route_status -file [file join $out_dir route_status_post_route.rpt]

set run_bit [file join $out_dir design_shiboqi_wrapper.bit]
write_bitstream -force $run_bit
write_debug_probes -force [file join $out_dir design_shiboqi_wrapper.ltx]
write_hw_platform -fixed -include_bit -force -file $xsa_file
file copy -force $run_bit $bit_copy

puts "BITSTREAM_FILE=$run_bit"
puts "BITSTREAM_COPY=$bit_copy"
puts "DIRECT_BUILD_DONE"
close_project
