
module ir_array_top_axi #(
  parameter int LANE_COUNT           = 1,
  parameter int MAX_PACKET_BYTES     = 256,
  parameter int FRAGMENT_BYTES       = 16,
  parameter int MAX_RETRY            = 4,
  parameter int CNT_CHIP_MAX         = 7,
  parameter int CNT_PREAMBLE         = 16,
  parameter int EOF_SILENCE_SYMS     = 3,
  parameter int FRAG_TIMEOUT_CYCLES  = 50000,
  parameter int REASSEMBLY_TIMEOUT_CYCLES = 200000,
  parameter int MAX_FRAGS            = (MAX_PACKET_BYTES + FRAGMENT_BYTES - 1) / FRAGMENT_BYTES,
  parameter int MAX_FRAME_BYTES      = (14 + FRAGMENT_BYTES),
  parameter int C_S_AXI_DATA_WIDTH   = 32,
  parameter int C_S_AXI_ADDR_WIDTH   = 6
)(
  input  logic                         clk_phy,
  input  logic                         rst_n,
  input  logic                         s_axi_aclk,
  input  logic                         s_axi_aresetn,
  input  logic [C_S_AXI_ADDR_WIDTH-1:0] s_axi_awaddr,
  input  logic                         s_axi_awvalid,
  output logic                         s_axi_awready,
  input  logic [C_S_AXI_DATA_WIDTH-1:0] s_axi_wdata,
  input  logic [3:0]                   s_axi_wstrb,
  input  logic                         s_axi_wvalid,
  output logic                         s_axi_wready,
  output logic [1:0]                   s_axi_bresp,
  output logic                         s_axi_bvalid,
  input  logic                         s_axi_bready,
  input  logic [C_S_AXI_ADDR_WIDTH-1:0] s_axi_araddr,
  input  logic                         s_axi_arvalid,
  output logic                         s_axi_arready,
  output logic [C_S_AXI_DATA_WIDTH-1:0] s_axi_rdata,
  output logic [1:0]                   s_axi_rresp,
  output logic                         s_axi_rvalid,
  input  logic                         s_axi_rready,
  input  logic [7:0]                   s_axis_tx_tdata,
  input  logic                         s_axis_tx_tvalid,
  output logic                         s_axis_tx_tready,
  input  logic                         s_axis_tx_tlast,
  output logic [7:0]                   m_axis_rx_tdata,
  output logic                         m_axis_rx_tvalid,
  input  logic                         m_axis_rx_tready,
  output logic                         m_axis_rx_tlast,
  output logic [LANE_COUNT-1:0]        ir_tx_out,
  input  logic [LANE_COUNT-1:0]        ir_rx_in,
  output logic [LANE_COUNT-1:0]        ir_sd,
  output logic [LANE_COUNT-1:0]        ir_mode_out
);
  logic cfg_enable;
  logic [15:0] cfg_session_id;
  logic [LANE_COUNT-1:0] cfg_lane_enable_mask;
  logic tx_packet_active, tx_packet_loading, tx_done_pulse, tx_error_overflow, tx_error_retry_exhausted;
  logic rx_ctx_valid, rx_ctx_complete, rx_done_pulse, rx_header_error, rx_protocol_error;
  logic [LANE_COUNT-1:0] lane_tx_busy_dbg;
  logic [MAX_FRAGS-1:0] tx_frag_pending_dbg, tx_frag_inflight_dbg, tx_frag_acked_dbg, rx_recv_bitmap_dbg;

  ir_axi_regs #(
    .C_S_AXI_DATA_WIDTH(C_S_AXI_DATA_WIDTH),
    .C_S_AXI_ADDR_WIDTH(C_S_AXI_ADDR_WIDTH),
    .LANE_COUNT(LANE_COUNT),
    .MAX_FRAGS(MAX_FRAGS)
  ) u_regs (
    .s_axi_aclk(s_axi_aclk),
    .s_axi_aresetn(s_axi_aresetn),
    .s_axi_awaddr(s_axi_awaddr),
    .s_axi_awvalid(s_axi_awvalid),
    .s_axi_awready(s_axi_awready),
    .s_axi_wdata(s_axi_wdata),
    .s_axi_wstrb(s_axi_wstrb),
    .s_axi_wvalid(s_axi_wvalid),
    .s_axi_wready(s_axi_wready),
    .s_axi_bresp(s_axi_bresp),
    .s_axi_bvalid(s_axi_bvalid),
    .s_axi_bready(s_axi_bready),
    .s_axi_araddr(s_axi_araddr),
    .s_axi_arvalid(s_axi_arvalid),
    .s_axi_arready(s_axi_arready),
    .s_axi_rdata(s_axi_rdata),
    .s_axi_rresp(s_axi_rresp),
    .s_axi_rvalid(s_axi_rvalid),
    .s_axi_rready(s_axi_rready),
    .cfg_enable(cfg_enable),
    .cfg_session_id(cfg_session_id),
    .cfg_lane_enable_mask(cfg_lane_enable_mask),
    .tx_packet_active(tx_packet_active),
    .tx_packet_loading(tx_packet_loading),
    .tx_done_pulse(tx_done_pulse),
    .tx_error_overflow(tx_error_overflow),
    .tx_error_retry_exhausted(tx_error_retry_exhausted),
    .rx_ctx_valid(rx_ctx_valid),
    .rx_ctx_complete(rx_ctx_complete),
    .rx_done_pulse(rx_done_pulse),
    .rx_header_error(rx_header_error),
    .rx_protocol_error(rx_protocol_error),
    .lane_tx_busy_dbg(lane_tx_busy_dbg),
    .tx_frag_pending_dbg(tx_frag_pending_dbg),
    .tx_frag_inflight_dbg(tx_frag_inflight_dbg),
    .tx_frag_acked_dbg(tx_frag_acked_dbg),
    .rx_recv_bitmap_dbg(rx_recv_bitmap_dbg)
  );

  ir_array_top #(
    .LANE_COUNT(LANE_COUNT),
    .MAX_PACKET_BYTES(MAX_PACKET_BYTES),
    .FRAGMENT_BYTES(FRAGMENT_BYTES),
    .MAX_RETRY(MAX_RETRY),
    .CNT_CHIP_MAX(CNT_CHIP_MAX),
    .CNT_PREAMBLE(CNT_PREAMBLE),
    .EOF_SILENCE_SYMS(EOF_SILENCE_SYMS),
    .FRAG_TIMEOUT_CYCLES(FRAG_TIMEOUT_CYCLES),
    .REASSEMBLY_TIMEOUT_CYCLES(REASSEMBLY_TIMEOUT_CYCLES),
    .MAX_FRAGS(MAX_FRAGS),
    .MAX_FRAME_BYTES(MAX_FRAME_BYTES)
  ) u_top (
    .clk_phy(clk_phy),
    .rst_n(rst_n),
    .enable(cfg_enable),
    .session_id(cfg_session_id),
    .lane_enable_mask(cfg_lane_enable_mask),
    .s_axis_tx_tdata(s_axis_tx_tdata),
    .s_axis_tx_tvalid(s_axis_tx_tvalid),
    .s_axis_tx_tready(s_axis_tx_tready),
    .s_axis_tx_tlast(s_axis_tx_tlast),
    .m_axis_rx_tdata(m_axis_rx_tdata),
    .m_axis_rx_tvalid(m_axis_rx_tvalid),
    .m_axis_rx_tready(m_axis_rx_tready),
    .m_axis_rx_tlast(m_axis_rx_tlast),
    .ir_tx_out(ir_tx_out),
    .ir_rx_in(ir_rx_in),
    .ir_sd(ir_sd),
    .ir_mode_out(ir_mode_out),
    .tx_packet_active(tx_packet_active),
    .tx_packet_loading(tx_packet_loading),
    .tx_done_pulse(tx_done_pulse),
    .tx_error_overflow(tx_error_overflow),
    .tx_error_retry_exhausted(tx_error_retry_exhausted),
    .rx_ctx_valid(rx_ctx_valid),
    .rx_ctx_complete(rx_ctx_complete),
    .rx_done_pulse(rx_done_pulse),
    .rx_header_error(rx_header_error),
    .rx_protocol_error(rx_protocol_error),
    .lane_tx_busy_dbg(lane_tx_busy_dbg),
    .tx_frag_pending_dbg(tx_frag_pending_dbg),
    .tx_frag_inflight_dbg(tx_frag_inflight_dbg),
    .tx_frag_acked_dbg(tx_frag_acked_dbg),
    .rx_recv_bitmap_dbg(rx_recv_bitmap_dbg)
  );
endmodule
